framework:
    rate_limiter:
        passwordRecovery:
            policy: 'token_bucket'
            limit: 100
            interval: '60 minutes'
            
            
        authenticated:
            policy: 'token_bucket'
            limit: 5000
            rate: { interval: '15 minutes', amount: 500 }